name: Build Extension

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: |
            ./
            !README.md
